
/control/verbose 0
/run/verbose 1
/tracking/verbose 0
/hits/verbose 1

/gps/pos/type Point
/gps/pos/centre 0 0 0 cm

/gps/particle neutron

/gps/ang/surfnorm 1
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 180 deg
/gps/ang/minphi 0 deg
/gps/ang/maxphi 360 deg

#/gps/ang/type user
#/gps/hist/type theta
#/gps/hist/file Sap7.5Poly3Pad10Theta.txt
#/gps/hist/inter Lin

#/gps/hist/type phi
#/gps/hist/point 0. 1.

/gps/ene/type User
/gps/hist/type energy
/gps/hist/file AmLiMeasuredPNNL.txt
#Sap7.5Poly3Pad10KE.txt
/gps/hist/inter Lin

/run/beamOn 9794

